version: '3'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    volumes:
      - ./logs:/app/logs
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "443:443"
    depends_on:
      - flask_app